name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Increase file descriptor limit
      run: ulimit -n 65536

    - name: Build and test with Gradle
      run: |
        ulimit -n 65536
        ./gradlew build --no-daemon --stacktrace --no-parallel --max-workers=1

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: joaquintown-mod-${{ github.sha }}
        path: build/libs/*.jar
        retention-days: 30

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ github.sha }}
        path: build/test-results/
        retention-days: 7
